services:
  backend:
    build: .
    container_name: backend
    restart: always
    ports:
      - "5000:5000"
    environment:
      - TZ=America/Argentina/Buenos_Aires
    depends_on:
      database:
        condition: service_healthy
    networks:
      - backend_network
    dns:
      - 1.1.1.1     # Cloudflare
      - 8.8.8.8     # Google
      - 9.9.9.9     # Quad9
    volumes:
      - ./logs:/app/logs 

  database:
    image: postgres:18
    container_name: backend_database
    restart: always
    ports:
      - "5432:5432"
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
      - POSTGRES_DB=excuses404
      - TZ=America/Argentina/Buenos_Aires
    volumes:
      - postgres_data:/var/lib/postgresql
      - ./.initdb:/docker-entrypoint-initdb.d:ro
    networks:
      - backend_network
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres"]
      interval: 5s
      timeout: 5s
      retries: 10

volumes:
  postgres_data:

networks:
  backend_network:
