-- Cleaned dump: only schema public with data
\connect excuses404;
SET search_path TO public;

--

CREATE FUNCTION public.register_account(
    p_username text,
    p_password text,
    p_first_name text,
    p_last_name text,
    p_telephone text,
    p_contact_email text
)
RETURNS integer
LANGUAGE plpgsql
AS $$
DECLARE
    v_user_id integer;
BEGIN
    BEGIN
        -- Insert into users
        INSERT INTO public.users (username, password, created_at)
        VALUES (p_username, p_password, NOW())
        RETURNING id INTO v_user_id;

        -- Insert into user_information
        INSERT INTO public.user_information (user_id, first_name, last_name, telephone, contact_email)
        VALUES (v_user_id, p_first_name, p_last_name, p_telephone, p_contact_email);

        -- Insert into user_roles (defaults role: "USER")
        INSERT INTO public.user_roles (user_id)
        VALUES (v_user_id);

        -- Insert into user_controls
        INSERT INTO public.user_controls (user_id)
        VALUES (v_user_id);

        -- Return generated user id
        RETURN v_user_id;

    EXCEPTION WHEN OTHERS THEN
        -- Rollback implicit in exception block
        RAISE NOTICE 'Error creating user: %', SQLERRM;
        RAISE; -- Re-throw to notify caller
    END;
END;
$$;


-- Update requests_id columns after some event
CREATE FUNCTION public.update_user_controls_flags() RETURNS trigger
    LANGUAGE plpgsql
    AS $$
BEGIN
    -- When user gets banned
    IF NEW.is_banned IS DISTINCT FROM OLD.is_banned THEN
        NEW.banned_at := CURRENT_TIMESTAMP;
    END IF;

    -- When user is forcefully disconnected
    IF NEW.force_disconnect IS DISTINCT FROM OLD.force_disconnect THEN
        NEW.disconnected_at := CURRENT_TIMESTAMP;
    END IF;

    -- When user is flagged as suspicious
    IF NEW.is_suspicious IS DISTINCT FROM OLD.is_suspicious THEN
        NEW.suspicious_at := CURRENT_TIMESTAMP;
    END IF;

    RETURN NEW;
END;
$$;

CREATE TABLE public.users (
    id integer GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    username varchar(50) NOT NULL UNIQUE,
    password varchar(150) NOT NULL,
    created_at timestamp NOT NULL,
    last_login_at timestamp,
    password_updated_at timestamp
);

CREATE TABLE public.roles (
    id integer GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    name varchar(17) NOT NULL UNIQUE
);

CREATE TABLE public.role_permissions (
    id integer GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    role_id integer NOT NULL,
    endpoint varchar NOT NULL,
    method varchar NOT NULL,
    CONSTRAINT fk_role_permissions_role
        FOREIGN KEY (role_id) REFERENCES public.roles (id)
        ON DELETE CASCADE,
    CONSTRAINT uq_role_permissions UNIQUE (role_id, endpoint, method)
);

CREATE TABLE public.user_roles (
    id integer GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    user_id integer NOT NULL,
    role_id integer DEFAULT 1 NOT NULL,
    CONSTRAINT fk_user_roles_user
        FOREIGN KEY (user_id) REFERENCES public.users (id)
        ON DELETE CASCADE,
    CONSTRAINT fk_user_roles_role
        FOREIGN KEY (role_id) REFERENCES public.roles (id)
        ON DELETE CASCADE,
    CONSTRAINT uq_user_roles UNIQUE (user_id, role_id)
);

CREATE TABLE public.user_information (
    user_id integer NOT NULL UNIQUE,
    first_name varchar(50) NOT NULL,
    last_name varchar(50) NOT NULL,
    telephone varchar(14) NOT NULL,
    contact_email varchar(100) NOT NULL,
    updated_at timestamp,
    CONSTRAINT fk_user_information_user
        FOREIGN KEY (user_id) REFERENCES public.users (id)
        ON DELETE CASCADE
);

CREATE TABLE public.user_controls (
    user_id integer NOT NULL UNIQUE,
    email_verified boolean DEFAULT false NOT NULL,
    email_verified_at timestamp,
    is_banned boolean DEFAULT false NOT NULL,
    banned_at timestamp,
    force_disconnect boolean DEFAULT false NOT NULL,
    disconnected_at timestamp,
    is_suspicious boolean DEFAULT false NOT NULL,
    suspicious_at timestamp,
    ban_request_id varchar(20),
    disconnect_request_id varchar(20),
    suspicious_request_id varchar(20),
    CONSTRAINT fk_user_controls_user
        FOREIGN KEY (user_id) REFERENCES public.users (id)
        ON DELETE CASCADE
);

CREATE TABLE public.otp_tokens (
    id integer GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    user_id integer NOT NULL,
    token varchar(6) NOT NULL,
    expires_at timestamp NOT NULL,
    type varchar(12) NOT NULL,
    CONSTRAINT fk_otp_tokens_user
        FOREIGN KEY (user_id) REFERENCES public.users (id)
        ON DELETE CASCADE,
    CONSTRAINT uq_otp_tokens_user_type UNIQUE (user_id, type)
);

CREATE TABLE public.requests (
    id varchar(20) PRIMARY KEY,
    user_id integer NOT NULL,
    method varchar(6) NOT NULL,
    endpoint varchar(100) NOT NULL,
    code varchar(4) NOT NULL,
    execution_time double precision NOT NULL,
    executed_at timestamp DEFAULT now() NOT NULL,
    CONSTRAINT fk_requests_user
        FOREIGN KEY (user_id) REFERENCES public.users (id)
        ON DELETE CASCADE
);

CREATE TABLE public.disciplines (
    id integer GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    name varchar(50) NOT NULL UNIQUE,
    intensity varchar(5) NOT NULL
);

CREATE TABLE public.locations (
    id integer GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    owner_id integer NOT NULL,
    country_code varchar(2) NOT NULL,
    city varchar(50) NOT NULL,
    address varchar(50) NOT NULL,
    created_at timestamp NOT NULL,
    updated_at timestamp,
    lat float NOT NULL,
    lng float NOT NULL,
    name varchar NOT NULL,
    CONSTRAINT fk_locations_owner
        FOREIGN KEY (owner_id) REFERENCES public.users (id)
        ON DELETE CASCADE,
    CONSTRAINT uq_locations UNIQUE (owner_id, name)
);

CREATE TABLE public.classes (
    id integer GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    professor_id integer NOT NULL,
    location_id integer NOT NULL,
    discipline_id integer NOT NULL,
    scheduled_at timestamp NOT NULL,
    started_at timestamp,
    ended_at timestamp,
    max_participants integer NOT NULL,
    qr varchar(150) NOT NULL,
    status varchar(11) DEFAULT 'NOT STARTED' NOT NULL,
    created_at timestamp,
    updated_at timestamp,
    CONSTRAINT fk_classes_professor
        FOREIGN KEY (professor_id) REFERENCES public.users (id)
        ON DELETE CASCADE,
    CONSTRAINT fk_classes_location
        FOREIGN KEY (location_id) REFERENCES public.locations (id)
        ON DELETE CASCADE,
    CONSTRAINT fk_classes_discipline
        FOREIGN KEY (discipline_id) REFERENCES public.disciplines (id)
        ON DELETE CASCADE
);

CREATE TABLE public.class_participants (
    id integer GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    class_id integer NOT NULL,
    user_id integer NOT NULL,
    confirmed_at timestamp,
    status varchar(13) DEFAULT 'NOT CONFIRMED' NOT NULL,
    added_at timestamp NOT NULL,
    updated_at timestamp,
    CONSTRAINT fk_class_participants_class
        FOREIGN KEY (class_id) REFERENCES public.classes (id)
        ON DELETE CASCADE,
    CONSTRAINT fk_class_participants_user
        FOREIGN KEY (user_id) REFERENCES public.users (id)
        ON DELETE CASCADE,
    CONSTRAINT uq_class_participants UNIQUE (class_id, user_id)
);

CREATE TABLE public.class_review (
    id integer GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    class_id integer NOT NULL,
    user_id integer NOT NULL,
    rating integer NOT NULL,
    message varchar(1000),
    reviewed_at timestamp NOT NULL,
    CONSTRAINT fk_class_review_class
        FOREIGN KEY (class_id) REFERENCES public.classes (id)
        ON DELETE CASCADE,
    CONSTRAINT fk_class_review_user
        FOREIGN KEY (user_id) REFERENCES public.users (id)
        ON DELETE CASCADE,
    CONSTRAINT uq_class_review UNIQUE (class_id, user_id)
);

CREATE TABLE public.subscriptions (
    id integer GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    user_id integer NOT NULL UNIQUE,
    subscribed_at timestamp NOT NULL,
    expires_at timestamp NOT NULL,
    CONSTRAINT fk_subscriptions_user
        FOREIGN KEY (user_id) REFERENCES public.users (id)
        ON DELETE CASCADE
);

CREATE TABLE public.subscription_information (
    id integer GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    subscription_id integer NOT NULL,
    paid_at timestamp NOT NULL,
    method varchar(10) NOT NULL,
    subscribed_before_paying timestamp NOT NULL,
    subscribed_after_paying timestamp NOT NULL,
    expiration_before_paying timestamp NOT NULL,
    expiration_after_paying timestamp NOT NULL,
    CONSTRAINT fk_subscription_information_subscription
        FOREIGN KEY (subscription_id) REFERENCES public.subscriptions (id)
        ON DELETE CASCADE
);

CREATE TABLE public.user_push_tokens (
    id integer GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    user_id integer NOT NULL,
    expo_push_token varchar(255) NOT NULL,
    last_used_at timestamp DEFAULT NULL,
    created_at timestamp DEFAULT NOW(),
    updated_at timestamp DEFAULT NULL,
    CONSTRAINT fk_user_push_tokens_user
        FOREIGN KEY (user_id) REFERENCES public.users (id)
        ON DELETE CASCADE,
    CONSTRAINT uq_user_push_token_user UNIQUE (user_id)
);

-- Users related tables
COPY public.users (id, username, password, created_at, last_login_at, password_updated_at) FROM stdin;
1	test01	$2b$12$F/Fg2evLtW6Z991XT4QkE.9BazVeYZj0jhBtkC2ApiuV7IcAAD9H6	2025-09-01 21:10:19.564016	\N	\N
2	test02	$2b$12$F/Fg2evLtW6Z991XT4QkE.9BazVeYZj0jhBtkC2ApiuV7IcAAD9H6	2025-09-01 21:12:51.629498	\N	\N
3	test03	$2b$12$F/Fg2evLtW6Z991XT4QkE.9BazVeYZj0jhBtkC2ApiuV7IcAAD9H6	2025-09-01 22:47:47.013712	\N	\N
4	test04	$2b$12$F/Fg2evLtW6Z991XT4QkE.9BazVeYZj0jhBtkC2ApiuV7IcAAD9H6	2025-09-01 22:52:16.440783	2025-09-22 09:23:27.212816	2025-09-21 19:20:14.031814
5	test05	$2b$12$F/Fg2evLtW6Z991XT4QkE.9BazVeYZj0jhBtkC2ApiuV7IcAAD9H6	2025-09-21 01:50:19.62771	\N	\N
6	test06	$2b$12$F/Fg2evLtW6Z991XT4QkE.9BazVeYZj0jhBtkC2ApiuV7IcAAD9H6	2025-09-21 01:56:12.04272	\N	\N
-1	adminn	$2b$12$F/Fg2evLtW6Z991XT4QkE.9BazVeYZj0jhBtkC2ApiuV7IcAAD9H6	2025-09-01 21:10:19.564	\N	\N
\.

COPY public.user_information (user_id, first_name, last_name, telephone, contact_email, updated_at) FROM stdin;
1	Ana	García	1112345678	ana.garcia@example.com	\N
2	Bruno	López	1198765432	bruno.lopez@example.com	\N
3	Carla	Martínez	1144556677	carla.martinez@example.com	\N
4	Diego	Fernández	1133344455	diego.fernandez@example.com	2025-09-27 09:57:44.405957
5	Elena	Pérez	1122233344	elena.perez@example.com	\N
6	Juan	Carlos	1166677788	juan.carlos@example.com	\N
-1	Francisco	Solé	1166677788	francisco.sole@example.com	\N
\.

COPY public.user_controls (
    user_id, email_verified, email_verified_at, is_banned, banned_at,
    force_disconnect, disconnected_at, is_suspicious, suspicious_at,
    ban_request_id, disconnect_request_id, suspicious_request_id
) FROM stdin;
1	f	\N	f	\N	f	\N	f	\N	\N	\N	\N
2	f	\N	t	2025-09-22 19:42:58.883699	f	\N	t	2025-09-22 19:41:53.328157	20250922194258547015	\N	20250922194219126952
3	f	\N	f	\N	f	\N	t	2025-09-22 08:59:53.491177	\N	\N	20250922085953306115
4	f	\N	f	\N	f	\N	f	\N	\N	\N	\N
5	f	\N	t	2025-09-23 10:00:00	f	\N	f	\N	20250923100000000001	\N	\N
6	f	\N	f	\N	f	\N	f	\N	\N	\N	\N
-1	t	\N	f	\N	f	\N	f	\N	\N	\N	\N
\.


-- Roles related tables
COPY public.roles (id, name) FROM stdin;
1	USER
2	BACKEND DEVELOPER
3	TRAINER
\.


COPY public.role_permissions (id, role_id, endpoint, method) FROM stdin;
1	1	/auth	POST
2	1	/auth/otp	POST
3	1	/classes	GET
4	1	/classes/upcoming	GET
5	1	/classes/<id>	GET
6	1	/classes/<id>/participant	POST
7	1	/classes/<id>/participant	DELETE
8	1	/otp	POST
9	1	/users	POST
10	1	/classes/<id>/participant/confirm	POST
11	3	/classes/<id>/	DELETE
13	1	/users	GET
14	1	/users	PUT
15	1	/classes/history	GET
16	1	/classes/history/<id>	GET
17	1	/classes/history/<id>/<id>	GET
18	1	/locations	GET
20	1	/otp/<id>	DELETE
21	1	/notifications/setUserToken	POST
22	3	/classes/<id>/start	POST
\.

COPY public.user_roles (id, user_id, role_id) FROM stdin;
1	1	3
2	2	3
3	3	1
4	4	1
5	5	1
6	6	1
7	-1	2
8	1	1
9	2	1
\.

-- Classes related tables
COPY public.disciplines (id, name, intensity) FROM stdin;
1	CrossFit	hard
2	Running	easy
\.

COPY public.locations (id, owner_id, country_code, city, address, created_at, updated_at, lat, lng, name) FROM stdin;
1	1	AR	1	asd	2025-09-04 23:58:04.639361	\N	-34.6175	-58.3808	Gimnasio Explosivo
2	2	AR	1	abc	2025-09-05 00:40:52.803678	\N	-34.6190	-58.3823	Gimnasio Montoto
3	3	AR	1	abc	2025-09-22 09:39:00.011519	\N	-34.6160	-58.3792	Gimnasio Diferenciado
\.

COPY public.classes (id, professor_id, location_id, discipline_id, scheduled_at, started_at, ended_at, max_participants, qr, status, created_at, updated_at) FROM stdin;
1	1	1	1	2025-09-03 02:25:00	\N	\N	50	abc	NOT STARTED	\N	\N
2	1	1	1	2025-09-30 02:25:00	\N	\N	50	123	NOT STARTED	\N	\N
3	1	1	1	2025-09-03 02:25:00	\N	\N	50	abc	NOT STARTED	2025-09-21 19:23:08.810045	\N
4	1	1	1	2025-09-03 02:25:00	\N	\N	50	abc	NOT STARTED	2025-09-21 19:23:53.581089	\N
5	2	1	2	2025-09-03 02:25:00	\N	\N	50	123	NOT STARTED	2025-09-20 16:03:08.593983	2025-09-20 16:23:04.330272
6	2	1	2	2025-09-03 02:25:00	\N	\N	50	abc	NOT STARTED	2025-09-21 19:21:40.593433	\N
7	2	2	2	2025-09-03 02:25:00	\N	\N	50	abc	NOT STARTED	2025-09-21 19:21:34.127179	\N
8	2	1	1	2025-09-03 02:25:00	\N	\N	50	abc	NOT STARTED	2025-09-21 19:21:34.127179	\N
\.

COPY public.class_participants (id, class_id, user_id, confirmed_at, status, added_at, updated_at) FROM stdin;
\.

COPY public.class_review (id, class_id, user_id, rating, message, reviewed_at) FROM stdin;
\.

-- OTP Tokens table
COPY public.otp_tokens (id, user_id, token, expires_at, type) FROM stdin;
\.

-- Subscriptions/payments related tables (we're not using it yet)
COPY public.subscriptions (id, user_id, subscribed_at, expires_at) FROM stdin;
\.

COPY public.subscription_information (id, subscription_id, paid_at, method, subscribed_before_paying, subscribed_after_paying, expiration_before_paying, expiration_after_paying) FROM stdin;
\.

-- Requests log table
COPY public.requests (id, user_id, method, endpoint, code, execution_time, executed_at) FROM stdin;
\.

CREATE TRIGGER trg_update_user_controls_flags BEFORE UPDATE ON public.user_controls FOR EACH ROW EXECUTE FUNCTION public.update_user_controls_flags();
